name: Update app version
on:
  push:
    tags:
      - "*"
jobs:
  build:
    name: Update Version
    runs-on: arc-runner-set
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Update app version in pyproject.toml
        shell: bash
        run: |
          git checkout -b main
          sed -i "s/^version = .*/version = \"${{github.ref_name}}\"/" pyproject.toml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add pyproject.toml
          git commit -m 'Update app version ${{github.ref_name}}'
          git branch -a
          git push origin main -f
